### ISSUE TITLE
`Bytecode` grammar

### ISSUE THREAD

**Issue by jbee** [bruno-lang/lingukit#18]
### Rough Idea

Design the grammar so that the special characters act as control codes or byte-codes. This is just elegant if each code is just a single character. Than there is e.g. a code for _the name is_, say `@`.
So when we write `@name` the `@` is the code that says: _now there follow characters for the name_. 
The first non-letter is (must be) the next byte-code (or space what is a _noop_  code).

The main advantage of this would be that it makes very clear how this works and how many commands are given through a particular grammar. Such a grammar though would need more conventions to be useful. E.g. all letters are also codes that mean _append to current name_ or such. From the above example the `@` is _starting a name_ and the letters do _append to name_.

This also suggests that capturing or naming is done by using `=` code. So a capture of a group is similar to capture of a rule.

    @rule = @foo @capture=(@bar @baz) @que

So the operation captures everything within the following block. If this is not a grouping block the next sequence is captured.

----

### Refinement
All "codes" are ASCII characters (hence a byte). Higher code points only occur as literal or as hexadecimal code point statement.

- selection: ... `|` ... `|`...
- group: `(` ... `)`
- optional group: `[` ... `]`
- character-set: `{` ... `}`
- capture: `<` _name_ `>`
- invert of character-set: `~` (e.g. `\n~`; only _use site_ inversion after a charset)
- repetition: 
 - `+` (once or more), 
 - `*` (zero or more), 
 - `?` (zero or once), 
 - `0`-`9` (exactly n times)
 - `-` (range as in `0-8`)
- lookahead: `^` (must be followed by a group or block)
- decision: `/`
- completion: `_`
- patterns (white-space; uses punctuation symbols):
 - _maybe WS_: `.`
 - _must be WS_: `:`
 - _maybe indent_: `,`
 - _must be indent_: `;`
 - _must be new line_: `!`
  (may => 1 shape, must => 2 shapes, indent => has `,`, must => has only `.` shape)
- as (name): `=`
- non-capturing reference: `&` (directly following a name)
- _no-op_: any white-space (ASCII; in fact those do _complete_ working state)
- interpretation mode
 - code: (bytes are op-codes)
 - literal: `'` ... `'` (eats bytes until next `'`, then creates a literal from it)
 - quote: `"` ... `"` (eats bytes until next `"`, then does *nothing*)
 - escape: `\` ... (eats bytes until white-space, the `\` is included here)
 - comment: `%` ... `%` (eats bytes until next `%` but does not add them to string register)
 - numeric: `{` makes letters (like digits) write their character code to numeric registers instead of string)

Predefined character sets: `\n`, `\t`, `\r`, `\s`, `\d`, `\z` (a-z), `\Z` (A-Z), `\F` (0-9, A-F), `\9` (0-9), `\.` ...

The interpreter is a loop consuming one byte/character at a time switching through the op-codes. 

This builds different kinds of partial states for:

- actual sequence (rule)
- actual literal
- actual name (of the build rule)
- total set of rules

When all bytes are consumed the list or set of rules is build in memory and has to be finished as usual to resolve references and improve the grammar.

**Comment by bar** [comment]
me? WAT?

**Comment by jbee** [comment]
I understand that this must sound confusing. But I gave it some more thought during the day and think it is actually a very good idea as it will remove the need for a grammar builder as grammars can directly be "parsed" by a very simple interpreter machine reading this "bytecode". While that is a "binary" code it will still be quite readable similar to how grammars are defined now. 

However, this explanation will most likely also not make much sense to someone else not able to see the model in my head. I guess you have to bear with me until I actually implement it.
Of course if you are seriously interested I can give you further detailed explanations but I guess you were just curious about this "strange" idea of mine.

**Comment by jbee** [comment]
@bar there https://github.com/bruno-lang/lingukit/commit/fb8e9b5623a1c0c8f1154cb0133de92dc2388f5a you go...

**Comment by bar** [comment]
@jbee ???
